AWSTemplateFormatVersion: 2010-09-09

Resources:
  AlifSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 22 ve 80 portu acildi
      SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 22
         ToPort: 22
         CidrIp: 0.0.0.0/0
       - IpProtocol: tcp
         FromPort: 80
         ToPort: 80
         CidrIp: 0.0.0.0/0  
  AlifHost:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      KeyName: first-key-pair
      SecurityGroupIds: 
       - !Ref AlifSecurityGroup
      Tags: 
       - Key: Name 
         Value: Alifidan
      UserData: 
        Fn::Base64: !Sub |
          #! /bin/bash
            yum update -y 
            yum install httpd -y 
            cd /var/www/html
            wget https://raw.githubusercontent.com/ali-fidan/projem1/main/index.html
            wget https://raw.githubusercontent.com/ali-fidan/projem1/main/foto1.jpg
            wget https://raw.githubusercontent.com/ali-fidan/projem1/main/foto2.jpg
            wget https://raw.githubusercontent.com/ali-fidan/projem1/main/foto3.jpg
            wget https://raw.githubusercontent.com/ali-fidan/projem1/main/arkaplan.jpg
            systemctl start httpd
            systemctl enable httpd


Outputs:
  WebSiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt AlifHost.PublicDnsName