AWSTemplateFormatVersion: 2010-09-09
Description: |
  alif

Resources:
  AlifSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AlifHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646
      InstanceType: t2.micro
      KeyName: first-key-pair
      SecurityGroupIds:
        - !Ref AlifSecurityGroup
      Tags:
        - Key: Name
          Value: alifidan
