AWSTemplateFormatVersion: 2010-09-09
Description: |
  OZGECMIS
Resources:
  FDNSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "22 VE 80"

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebserverFDN:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646

      InstanceType: t2.micro

      KeyName: first-key-pair

    SecurityGroups:
      - !Ref FDNSecGrp
    Tags:
      - Key: Name
        Value: !Sub Web Server of ${AWS::StackName}

    UserData:
      Fn::Base64: !Sub |
        #! /bin/bash
           yum update -y
           yum install httpd -y
           FOLDER=https://raw.githubusercontent.com/ali-fidan/projem1/master
           cd /var/www/html
           wget $FOLDER/tonystark.html
           wget $FOLDER/tony.yaml
           wget $FOLDER/foto1.jpg
           wget $FOLDER/foto2.jpg
           wget $FOLDER/foto3.jpg
           wget $FOLDER/arkaplan.jpg
           systemctl start httpd
           systemctl enable httpd

Outputs:
  WebSiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
